#include "nuc123.h"
#include "drv_nuc123.h"

void NUC123_Init(void)
{
	/*
IO MAPPING
NUC123.PA10 --- MCP4725.SDA
NUC123.PA11 --- MCP4725.SCL
*/
#if 0
	SYS->GPA_MFP &= ~(SYS_GPA_MFP_PA10_Msk | SYS_GPA_MFP_PA11_Msk );
	SYS->GPA_MFP |= (SYS_GPA_MFP_PA10_I2C1_SDA | SYS_GPA_MFP_PA11_I2C1_SCL );

	SYS->ALT_MFP &= ~(SYS_ALT_MFP_PA10_Msk |SYS_ALT_MFP_PA11_Msk );
	SYS->ALT_MFP |= (SYS_ALT_MFP_PA10_I2C1_SDA |SYS_ALT_MFP_PA11_I2C1_SCL );	
	
#endif	
#if 1
	//set PB7 GPIO push pull
	SYS->GPB_MFP &= ~(SYS_GPB_MFP_PB7_Msk | SYS_GPB_MFP_PB6_Msk | SYS_GPB_MFP_PB5_Msk | SYS_GPB_MFP_PB4_Msk);
	SYS->GPB_MFP |= (SYS_GPB_MFP_PB7_GPIO | SYS_GPB_MFP_PB6_GPIO | SYS_GPB_MFP_PB5_GPIO | SYS_GPB_MFP_PB4_GPIO);

	SYS->ALT_MFP &= ~(SYS_ALT_MFP_PB7_Msk |SYS_ALT_MFP_PB6_Msk |SYS_ALT_MFP_PB4_Msk |SYS_ALT_MFP_PB5_Msk);
	SYS->ALT_MFP |= (SYS_ALT_MFP_PB7_GPIO |SYS_ALT_MFP_PB6_GPIO |SYS_ALT_MFP_PB5_GPIO |SYS_ALT_MFP_PB4_GPIO);
	
	GPIO_SetMode(PB,BIT7|BIT6|BIT5|BIT4,GPIO_PMD_OUTPUT);
	PB6=0;
	PB4=0;
	PB7=0;
	PB5=0;

	
	SYS->GPD_MFP &= ~(SYS_GPD_MFP_PD1_Msk | SYS_GPD_MFP_PD2_Msk | SYS_GPD_MFP_PD3_Msk | SYS_GPD_MFP_PD4_Msk);
	SYS->GPD_MFP |= (SYS_GPD_MFP_PD1_GPIO | SYS_GPD_MFP_PD2_GPIO | SYS_GPD_MFP_PD3_GPIO | SYS_GPD_MFP_PD4_GPIO);

	SYS->ALT_MFP &= ~(SYS_ALT_MFP_PD1_Msk |SYS_ALT_MFP_PD2_Msk |SYS_ALT_MFP_PD3_Msk |SYS_ALT_MFP_PD4_Msk);
	SYS->ALT_MFP |= (SYS_ALT_MFP_PD1_GPIO |SYS_ALT_MFP_PD1_GPIO |SYS_ALT_MFP_PD1_GPIO |SYS_ALT_MFP_PD1_GPIO);
	GPIO_SetMode(PD,BIT1|BIT2|BIT3|BIT4,GPIO_PMD_INPUT);
#endif



}

